version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
    environment:
      - API_TOKEN=${API_TOKEN}
    depends_on:
      - db
    entrypoint: ["sh", "-c", "python /app/init_db.py && python /app/bot.py"]

  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/var/lib/sqlite3

volumes:
  db_data: